version: "3"
services:
  db:
    image: "postgres:11.7"
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_DB=reckon_test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
